---
- name: Provisioning VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu
  
  tasks:
    - import_tasks: pam_pwquality.yml
    - import_tasks: user_and_groups.yml
    - import_tasks: file_creation.yml
    - import_tasks: nginx_setup_automation.yml