  - name: set name
    set_fact:
      username: kas
  
  - name: print name
    debug:
      msg: "Hi {{ username }}"

  - name: list of facts available on system
    debug:
      var: ansible_facts.distribution

  - name: check date for setting facts
    set_fact: 
      check_date: "{{ ansible_date_time.date | to_datetime('%Y-%m-%d') > ('2022-03-01' | to_datetime('%Y-%m-%d')) }}"

  - name: get OS name
    set_fact:
      os_name: "{{ ansible_distribution == 'CentOS' }}"

  - name: if time is more than 2025-03-01 on server it will do something (say todays date)
    debug:
      msg: 'hi {{ ansible_date_time.date }}'
    when: check_date

  - name: OS check with set_fact
    debug:
      msg: 'OS is Ubuntu'
    when: os_name

  - name: OS check without set_fact
    debug:
      msg: 'OS is Ubuntu'
    when: ansible_distribution == 'Ubuntu'
