- name: Uninstall nginx on server
  apt:
    name: nginx
    state: absent
  become: yes

- name: Install nginx on server
  apt:
    name: nginx
    state: latest
  become: yes

- name: Place the new configuration
  copy:
    src: ./nginx_conf/index.html
    dest: /var/www/html/index.nginx-debian.html
    force: yes
  become: yes
      
- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: yes